### ISSUE TITLE
/lyrics description length

### ISSUE THREAD

**Issue by JustLian** [JustLian/HoriBot#4]
**Describe the bug**
Command /lyrics cant disaplay lyrics of some songs

**To Reproduce**
1. Choose song with long lyrics
2. Find that song lyrics with /lyrics commans

**Expected behavior**
Message with song lyrics

**Additional context**
```
           Ignoring exception in command lyrics:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nextcord/application_command.py", line 1053, in _call_with_hooks
    await callback(*args)
  File "/usr/local/lib/python3.10/dist-packages/nextcord/application_command.py", line 1135, in call_invoke_slash
    await self.invoke_slash(interaction, **kwargs)                        File "/usr/local/lib/python3.10/dist-packages/nextcord/application_command.py", line 1226, in invoke_slash
    await self.callback(self._self_argument, interaction, **kwargs)       File "/root/HoriBot/hori/cogs/main.py", line 53, in cmd_lyrics
    await inter.edit_original_message(embed=em)
  File "/usr/local/lib/python3.10/dist-packages/nextcord/interactions.py", line 417, in edit_original_message
    data = await adapter.edit_original_interaction_response(
  File "/usr/local/lib/python3.10/dist-packages/nextcord/webhook/async_.py", line 191, in request
    raise HTTPException(response, data)
nextcord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.description: Must be 4096 or fewer in length.
```

**Comment by JustLian** [comment]
Fixed in 1e1f27954c51226a298e0ea836bf3684c58ff1e5
